name: AutoBroadcaster
version: ${project.version}
main: com.github.evancolewright.autobroadcaster.AutoBroadcaster
softdepend: [ PlaceholderAPI ]
authors: [ evancolewright ]
description: A basic multi-line auto-broadcaster with PAPI support.
